### PR TITLE
Support django 4.x

### PR DESCRIPTION
**Pull request by spapas**
Hello @jpic could you please merge this PR so we'll have django 4.x compatibility? 

TIA !

### CODE REVIEW

**Comment by spapas** [comment]
Hello again @jpic any news about merging this and releasing a new version ? Thank you !

**Comment by jpic** [comment]
Hi @spapas !

Sorry for the delay!

Released 0.3.1 ;)

Take care old friend!!

**Comment by spapas** [comment]
@jpic thank you so much!!! I am using it in like 10 projects and it's a pain using the github dependency :)

Kind regards,
Serafeim

**Comment by jpic** [comment]
Sure thing!! What's your Pypi username?

**Comment by spapas** [comment]
Serafeim.Papastefanos - https://pypi.org/user/Serafeim.Papastefanos/

**Comment by jpic** [comment]
Added you as maintainer!

**Comment by spapas** [comment]
Thank you very much @jpic  ! I'll keep this up to date because I use it to almost all of my projects :)

**Comment by jpic** [comment]
Thanks! You got this!

:tophat:

**Pull request merged**
