### PR TITLE
Add django 1.8 support

### PR DESCRIPTION
**Pull request by spapas**
For compatibility with django 1.8, see
https://docs.djangoproject.com/fr/1.8/internals/deprecation/#deprecation-removed-in-1-8

### CODE REVIEW

**Comment by spapas** [comment]
Well this PR started as small two lines changes (see 44d2a09) to change the (deprecated) ``_meta.module_name`` to ``_meta.model_name``. However, after submitting the PR I noticed that there was travis-ci integration with support for older versions that had the old syntax. 

So I added a try/catch check to support all versions of django from 1.4 and added django 1.8 in travis.yml (see 206f6a5). However, the TEST_RUNNER that was used was also removed in django 1.8 (it was deprecated in django 1.6) so I added a check in test_project/settings.py to use the new TEST_RUNNER in django version >= 1.6 (see 2f68994).

Finally, all is green now and django-rules-light will have django 1.8 support :+1:

**Comment by jpic** [comment]
Awesome ! I'll release it this week end

**Comment by spapas** [comment]
Goody! Looking forward to it, thanks a lot @jpic!

**Comment by jpic** [comment]
Released in 0.1.3. Thanks for your contribution B)

**Pull request merged**
