### PR TITLE
Prepare 0.3.0 release

### PR DESCRIPTION
**Pull request by spapas**
Hello @jpic it should be ready for adding version 0.3.0 to pypi now, thanks!

### CODE REVIEW

**Comment by spapas** [comment]
Hello @jpic any updates on when the 0.3.0 release will be added to pypi? I'd like to remove `-e git+https://github.com/spapas/django-rules-light.git` from my requirements files!

**Comment by jpic** [comment]
Well there are still some problems: 

2019-04-11-181146_1091x368_scrot

But go ahead and merge when you are ready and ping me somewhere (preferably on yourlabs.chat ) and i will publish the release !

Sorry for the late reply

**Comment by jpic** [comment]
PS: if you are tired with flake8 / manually beautifying the code, feel free to move to github.com/ambv/black instead.

**Comment by spapas** [comment]
Hello @jpic thanks for the heads up, I am already using black for some projects and I agree it's great. 

I fixed the pep8 errors and now it throws a random error for missing an sqlitev version dependency but only for py36-django110 (while it works for py36-django19 and django111) ! This is really strange and probably can be ignored.

**Comment by spapas** [comment]
Thank you @jpic for the merge and new release!

Now I can finally remove all 

-e git+https://...

django-rules-light requirements from my projects :)

**Pull request merged**
