### PR TITLE
Changes to make tests pass

### PR DESCRIPTION
**Pull request by spapas**

### CODE REVIEW

**Comment by spapas** [comment]
Hey @jpic, I've made the required changes to pass tests along with a bunch of changes to tox.ini (upgrade to python 3.7, remove django < 1.8, add django 2x). Everything seems to be working fine in my dev env however for whatever reason travis-ci keeps using *the old* tox.ini (https://travis-ci.org/yourlabs/django-rules-light/builds/474761057/config) and the tests for some configurations are failing. Do you have any idea why is that? 

I'll try adding a new small commit to this PR to see if maybe now travis re-reads the configuration.

**Comment by spapas** [comment]
Ok it seems that I'd forgotten to change .travis.yml! Now travis seems to have a problem with python 3.7. I'lll change it to 3.6 and retry...

**Comment by jpic** [comment]
Nice one @spapas, what next the pypi release ?

**Comment by spapas** [comment]
Thanks @jpic. I'm not sure I understand should I do anything else ?

**Comment by spapas** [comment]
I don't think that I have permissions to merge this PR. Also I'd rather you do the pypi release if you don't mind :)

**Comment by jpic** [comment]
You should have write permission now. In general I prefer to let contributors merge when they see fit because they should be ready in case there is user feedback. Just open an issue when you need a pypi release and do ping me. Otherwise, we can move to yourlabs.io where we have automated pypi uploads on git tag push !

**Comment by spapas** [comment]
Ok I understand!

Before merging I think that some changes would also be needed to the README (remove non-supported versions etc). Should I add them ?

**Comment by jpic** [comment]
It's all yours, I use my own [custom security backend](https://yourlabs.io/oss/crudlfap/blob/master/src/crudlfap_auth/backends.py) which lets me set ViewClass.allowed_groups, in addition my view classes being [crudlfap.Route](https://crudlfap.readthedocs.io/en/latest/route.html) too.
I just need to know when you want a PyPi release

**Pull request closed without merging**
