### PR TITLE
Improved django 1.8 support!

### PR DESCRIPTION
**Pull request by spapas**
The new test runner of django 1.6 (that had to be used for django 1.8) did not automatically discover  tests from test/__init__py, so the tests *were not*  running for django 1.8 :( 

To fix that, all test modules  were renamed to start with test_* so now they are  discovered.

Unfortuanately, this leaded to a bunch of tests failing in django 1.8 because:

 - the fields attribute is required in a CBV please see https://docs.djangoproject.com/en/1.8/releases/1.8/#miscellaneous
(fixed in module tests.class_decorator_classes by adding all fields of the User class)
 - the get_form doesn't require the form_class parameter anymore, please see https://docs.djangoproject.com/en/1.8/releases/1.8/#generic-views
(fixed in module class_decorator by checking if version >= 1.8 and defining the new_get_form method accordingly)

### CODE REVIEW

**Comment by jpic** [comment]
Nice ongoing work.

Another solution to support all django versions is to use tox and
pytest-django like in django-autocomplete-light, it'll take a bit of time I
guess, but then it's really awesome.

**Comment by spapas** [comment]
Hello @jpic, the tests seem to fail because of the different test runner (``django.test.runner.DiscoverRunner``) that is used in django 1.8. The really strange thing is that I am using django 1.8 to run the tests in my development environment and everything is ok !

Do you have any idea about why the travis tests fail while the tests on my environment pass ?

**Comment by jpic** [comment]
On Wed, Apr 22, 2015 at 1:02 PM, Serafeim Papastefanos <
notifications@github.com> wrote:

> Hello @jpic <https://github.com/jpic>, the tests seem to fail because of
> the different test runner (django.test.runner.DiscoverRunner) that is
> used in django 1.8.
>

Yep, so that's why using pytest-django as test runner works for
django-autocomplete-light from django 1.4 to 1.9 (django-master): because
we're using pytest as runner and not django.

With tox it's even better because tox is able to generate all environment
like travis.

> The really strange thing is that I am using django 1.8 to run the tests in
> my development environment and everything is ok !
>
> Do you have any idea about why the travis tests fail while the tests on my
> environment pass ?
>
It looks to me that travis does run the tests on django 1.8:

https://travis-ci.org/yourlabs/django-rules-light/jobs/59531661

But, autodiscover seems to not be called at all. In
django-autocomplete-light, we got rid of the autodiscover() call for django
>= 1.6 with autocomplete_light/apps.py

So, for django 1.8, you might want to call autodiscover() manually
whereever the tests require it.

-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by spapas** [comment]
I changed the class of ``AutodiscoverTestCase`` from ``unittest.TestCase`` to ``django.test.TestCase`` (in order to be run before the other tests so that ``autodiscover`` will run first, see https://docs.djangoproject.com/en/1.8/topics/testing/overview/#order-in-which-tests-are-executed). Now, it seems that only the test for python 2.7 - django 1.8 fails but for a non-related reason (!)

**Comment by jpic** [comment]
Are you talking about that one ?

https://travis-ci.org/yourlabs/django-rules-light/jobs/59537053

Apparently it can't find the users in question in the database, which means
that they haven't been inserted.

Objects are inserted in the database for tests usually through fixtures or
in setUp.

**Comment by spapas** [comment]
@jpic yes I'm talking about that one. How is it possible that objects will be inserted on all other test cases and *not* on that particular one ? Especially since objects are inserted in the ``setUp`` method of the test ?

**Comment by jpic** [comment]
Merged on master, tested with tox, and also passing flake8.

```
$ tox
  py27-django15: commands succeeded
  py27-django16: commands succeeded
  py27-django17: commands succeeded
  py27-django18: commands succeeded
ERROR:   py27-djangomaster: commands failed
  py34-django15: commands succeeded
  py34-django16: commands succeeded
  py34-django17: commands succeeded
  py34-django18: commands succeeded
ERROR:   py34-djangomaster: commands failed
  py27-django14: commands succeeded
```

Try running tests with the `tox` command (pip installable) on master and check it out, it's way cool, credits @blueyed for the code.

Just need to support django19 (`tox -e py34-djangomaster`), add a default_app and document that calling `autodiscover()` has become optionnal and we're good to make a fine release.

**Comment by jpic** [comment]
Django 1.7's default_app implemented (no need to call autodiscover manually
anymore), Django 1.8 tested, Django 1.9 thrown in while i was at it,
django-rules-light 0.2.0 released.

Thanks a heap for your help, your knowledge about django-rules-light is
valuable, I'd like to invite you as contributor so that you could work on
branches of the upstream repo instead of having to fork, keep up the good
work.

Rock'on B)

**Comment by jpic** [comment]
Oh, you're there already, I just remembered we have worked together on
this a few years ago xD

Feel free to join us on IRC: #yourlabs on irc.freenode.net

**Comment by spapas** [comment]
@jpic thanks a lot! 

And thanks for django-rules-light it is a really great django add-on, I am using it in all my projects that need to enforce per-object business rules :+1:

**Pull request merged**
